### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by haran4597** [nghorbani/amass#1]
HI SIR,
When I am trying to run the tutorial , I'm getting an error stating that
TypeError: __init__() missing 1 required positional argument: 'model_type'
Help me to rectify this error

**Comment by AmmarkoV** [comment]
I have the same issue

python3 test.py 
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    bm = BodyModel(bm_path=bm_path, num_betas=num_betas, num_dmpls=num_dmpls, path_dmpl=dmpl_path).to(comp_device)
TypeError: __init__() missing 1 required positional argument: 'model_type'

When running the following script ( extension changed from .py to .txt so it could be uploaded to github )
[test.txt](https://github.com/nghorbani/amass/files/3927091/test.txt)

**Comment by nghorbani** [comment]
please pull the latest changes of the repository and try again. you are using an outdated version of the repo.
Nima

**Comment by nghorbani** [comment]
I mean the human_body_prior, e.g. run the following command in your environment:
pip install -U git+https://github.com/nghorbani/human_body_prior
