### ISSUE TITLE
MPI Limits on notebook 02-AMASS_DNN

### ISSUE THREAD

**Issue by arturbecker** [nghorbani/amass#12]
Hi, thanks for providing this repository!
I can't find the **MPI_Limits** dataset on the AMASS dataset page, do you know if it goes by another name there or has been pulled off?

Specifically, it is called in the example notebook, **02-AMASS_DNN** on code block 5:
`amass_splits = {
    'vald': ['HumanEva', 'MPI_HDM05', 'SFU', 'MPI_mosh'],
    'test': ['Transitions_mocap', 'SSM_synced'],
    'train': ['CMU', 'MPI_Limits', 'TotalCapture', 'Eyes_Japan_Dataset', 'KIT', 
              'BML', 'EKUT', 'TCD_handMocap', 'ACCAD']
}
amass_splits['train'] = list(set(amass_splits['train']).difference(set(amass_splits['test'] + amass_splits['vald'])))`

**Comment by nghorbani** [comment]
Hi, that would be PosePrior. Good catch, we should fix this in an upcoming update
