### ISSUE TITLE
Is it possible to have only some parts of the body?

### ISSUE THREAD

**Issue by marmg** [nghorbani/amass#17]
Hi, 

I would like to use this but only with hands/feet, is it possible to have only these parts of the body?

Thanks!

**Comment by nghorbani** [comment]
if you still need it here you can find the indices for various body parts of SMPLH model: 
[part2vids.zip](https://github.com/nghorbani/amass/files/6474014/part2vids.zip)
and a visualization:
![part2vids](https://user-images.githubusercontent.com/7373673/118161241-a464fe00-b41f-11eb-8e71-90c285fb1e8e.png)
this is a partial snippet to produce the image:
`    
from psbody.mesh.meshviewer import MeshViewer
mv = MeshViewer(keepalive=True)
meshes = [Mesh(v=body_v[part2vids[partname]], f=[], vc=part_vc) for partname, part_vc in body_part_vc.items()]
mv.set_static_meshes(meshes)
`
I hope this helps.
