### ISSUE TITLE
ContextException: Could not create GL context

### ISSUE THREAD

**Issue by ljq2020** [nghorbani/amass#21]
Hi, 
I am running ` amass/notebooks/01-AMASS_Visualization.ipynb`, and I met a error.

![1](https://user-images.githubusercontent.com/63891270/112110354-be3b4f00-8bed-11eb-87b3-a4059046cd94.png)
![2](https://user-images.githubusercontent.com/63891270/112110374-c4313000-8bed-11eb-8a32-989ffe496c1d.png)

Any idea on how to fix it would be helpful.

**Comment by nghorbani** [comment]
could you see if this helps? https://en.wikibooks.org/wiki/OpenGL_Programming/Installation/Linux
To me it seems there might be an issue with OpenGL installation

**Comment by itswyri** [comment]
I encountered the same problem and

https://github.com/mmatl/pyrender/issues/13#issuecomment-829068560

solves the issue.
