### ISSUE TITLE
ImportError: cannot import name 'colors' from 'human_body_prior.tools.omni_tools' 

### ISSUE THREAD

**Issue by amituofo1996** [nghorbani/amass#22]
Hi,
I am running amass/notebooks/01-AMASS_Visualization.ipynb, and I met a error
![image](https://user-images.githubusercontent.com/49180284/118234646-36274680-b4c6-11eb-8cd3-bf9455550b7a.png)
Any idea on how to fix it would be helpful.

**Comment by nghorbani** [comment]
I fixed the code and ran the notebooks to double check. Please update [human_body_prior ](https://github.com/nghorbani/human_body_prior) and [body_visualizer ](https://github.com/nghorbani/body_visualizer). sorry for the inconvenience.
