### ISSUE TITLE
Kernel dying on loading on import of the required files for viewing out mesh

### ISSUE THREAD

**Issue by MichaelaBrezinova** [nghorbani/amass#5]
Hi,
My kernel is crashing on importing of MeshViewer from human_body_prior when trying to run 01-AMASS_Visualization notebook.

Do you know why this might be happening?

Thank you!
Michaela

**Comment by MichaelaBrezinova** [comment]
I have narrowed down the problem to mv = MeshViewer(width=imw, height=imh, use_offscreen=True)

**Comment by quyanqiu** [comment]
The issue might be occured when you use pyrender to do visualization,similar problem happended in smpl-x project,try to set visualization to false and use some other differentialable renderer such as DIB-R or SoftRas.
By the way,pyrender is always tough for me , if you are using ssh to server for offscreen rendering,try use other rendering tools insteal of pyrender.

**Comment by nghorbani** [comment]
@MichaelaBrezinova do you still experience the issue? On my side all the notebooks run clean. I would suggest installing all the dependencies from their respective git repository and try again. Please drop me an status update. thanks

**Comment by MichaelaBrezinova** [comment]
Hi, I apologize for the belated reply. I reinstalled the dependencies and it seems to be running smoothly now. I guess something was not installed properly. Thank you for the help!
