### ISSUE TITLE
AssertionError when trying to run 02-AMASS_DNN - Jupyter Notebook

### ISSUE THREAD

**Issue by haran4597** [nghorbani/amass#7]
AssertionError                            Traceback (most recent call last)
<ipython-input-6-7d8214e61eac> in <module>
      1 from amass.prepare_data import prepare_amass
----> 2 prepare_amass(amass_splits, amass_dir, work_dir, logger=logger)

~/.local/lib/python3.6/site-packages/amass/prepare_data.py in prepare_amass(amass_splits, amass_dir, work_dir, logger)
    156         outpath = makepath(os.path.join(stageI_outdir, split_name, 'pose.pt'), isfile=True)
    157         if os.path.exists(outpath): continue
--> 158         dump_amass2pytroch(datasets, amass_dir, outpath, logger=logger)
    159 
    160     logger('Stage II: augment the data and save into h5 files to be used in a cross framework scenario.')

~/.local/lib/python3.6/site-packages/amass/prepare_data.py in dump_amass2pytroch(datasets, amass_dir, out_posepath, logger, rnd_seed, keep_rate)
     97             data_gender.extend([gdr2num[str(cdata['gender'].astype(np.str))] for _ in cdata_ids])
     98 
---> 99     assert len(data_pose) != 0
    100 
    101     torch.save(torch.tensor(np.asarray(data_pose, np.float32)), out_posepath)

AssertionError:

**Comment by TalBarami** [comment]
Hey,
I am having the exact same error. Did you manage to solve it?
